### ISSUE TITLE
Several error by install module

### ISSUE THREAD

**Issue by madeinfree** [KKBOX/OpenAPI-JavaScript#1]
Thanks for KKBOX OpenAPI.

I run into some problem when I use it to nodejs server, but I don't know this is the problem or not thus I open a issue to figure out them~

- I following the README to import 'kkbox-javascript-developer-sdk' and get the error.

```javascript
import { Auth } from 'kkbox-javascript-developer-sdk' // Cannot find module 'kkbox-javascript-developer-sdk';
//change into
import { Auth } from '@kkboxorg/kkbox-javascript-developer-sdk'; // work
```

- I use nodejs require but the SDK doesn't compile in npm module cause the `Unexpected token export` error, may it be possible compile to npm module with es5 ?

```javascript
const { Auth } = require('@kkboxorg/kkbox-javascript-developer-sdk'); // Unexpected token export
```

**Comment by willyliu** [comment]
Thanks for your feedback, we are looking into it.

**Comment by willyliu** [comment]
Alright, we have fixed it in the latest version, please try again. Previously we published the es6 version of sdk and hence you cannot require it in node, now we have changed to correctly publish es5 version of sdk.

**Comment by madeinfree** [comment]
Thanks @willyliu, I'll try later 👍

**Comment by ajhsu** [comment]
Hi @madeinfree ,

Is everything works fine? :)
I'm going to close the issue; If you have further question, please let us know :)
